version: '3.8'

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy-server
    command:
      - serve
    environment:
      - NTFY_BASE_URL=https://ntfy.yourdomain.com
      - NTFY_LISTEN_HTTP=:80
      - NTFY_CACHE_FILE=/var/lib/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_AUTH_DEFAULT_ACCESS=read-write
      - NTFY_BEHIND_PROXY=true
      - NTFY_ENABLE_SIGNUP=true
      - NTFY_ENABLE_LOGIN=true
    volumes:
      - ./server.yml:/etc/ntfy/server.yml:ro
      - ntfy_data:/var/lib/ntfy
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/v1/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ntfy_data: